//api1
POST http://localhost:3000/register/
Content-Type: Application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

//api2
POST http://localhost:3000/login/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwMzI0MzY2fQ.EVGutGaDPR3pYA5tjK4lEPVh1TPkw24eL6dozWJcbtc
Content-Type: Application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

//api3
GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwMzI0MzY2fQ.EVGutGaDPR3pYA5tjK4lEPVh1TPkw24eL6dozWJcbtc

//api4
GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwMzI0MzY2fQ.EVGutGaDPR3pYA5tjK4lEPVh1TPkw24eL6dozWJcbtc

//api5
GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwMzI0MzY2fQ.EVGutGaDPR3pYA5tjK4lEPVh1TPkw24eL6dozWJcbtc

//api6
GET http://localhost:3000/tweets/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwMzI0MzY2fQ.EVGutGaDPR3pYA5tjK4lEPVh1TPkw24eL6dozWJcbtc

//api7
GET http://localhost:3000/tweets/4/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwMzI0MzY2fQ.EVGutGaDPR3pYA5tjK4lEPVh1TPkw24eL6dozWJcbtc

//api8
GET http://localhost:3000/tweets/4/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwMzI0MzY2fQ.EVGutGaDPR3pYA5tjK4lEPVh1TPkw24eL6dozWJcbtc

//api9
GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwMzI0MzY2fQ.EVGutGaDPR3pYA5tjK4lEPVh1TPkw24eL6dozWJcbtc

//api10
POST http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwMzI0MzY2fQ.EVGutGaDPR3pYA5tjK4lEPVh1TPkw24eL6dozWJcbtc
Content-Type: Application/json

{
   "tweet": "The Mornings..."
}

//api11
DELETE http://localhost:3000/tweets/7/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzIwMzI0MzY2fQ.EVGutGaDPR3pYA5tjK4lEPVh1TPkw24eL6dozWJcbtc
